### ISSUE TITLE
Can't install the API, setup.py missing

### ISSUE THREAD

**Issue by arthurpattee** [KonradIT/gopro-py-api#1]
@KonradIT Hi ! I'm trying to install your library however I'm getting an error since there is no setup.py file :/

**Comment by KonradIT** [comment]
Hi, I know, right now just use the commands:

```
from goprocam import GoProCamera
from goprocam import constants
gopro = GoProCamera.GoPro() #recommended: add constants.gpcontrol for HERO4/5 or constants.auth for HERO3/3+

...
```

The setup will be added later on.

**Comment by arthurpattee** [comment]
New error, when trying to import GoProCamera returns 'No module named request' (is there a library to install? I do babe urllib running though )

**Comment by KonradIT** [comment]
@arthurpattee make sure you're running python 3.

**Comment by arthurpattee** [comment]
@KonradIT I was using python 2.7, seems to be better with 3.0 indeed, yet still an error when lancing gopro = GoProCamera.GoPro()
-> the JSON object must be str, not 'bytes'

**Comment by KonradIT** [comment]
@arthurpattee I'm using Python 3.6.0.

What camera are you using?

**Comment by arthurpattee** [comment]
@KonradIT I'm using python 3.5.2 and I've tried with a Hero 5 Session and a hero 4 black, same respond on both

**Comment by KonradIT** [comment]
@arthurpattee 

Then use: 
    
    gopro = GoProCamera.GoPro(constants.gpcontrol)

**Comment by arthurpattee** [comment]
@KonradIT Same error, but at slightly different line I noticed, it starts with a Waking up... message then the JSON object..

**Comment by KonradIT** [comment]
@arthurpattee just pushed a fix, hope it works. Please pull the latest changes and try again. Also, tell me which line exactly.

**Comment by arthurpattee** [comment]
@KonradIT it works ! Thank you very much! If I can do something to help debug let me know! 😊
