### ISSUE TITLE
Traceback (most recent call last):   File "./gopro-py-api/examples/launch_webcam_preview.py", line 6,

### ISSUE THREAD

**Issue by lukiifaz** [KonradIT/gopro-py-api#156]
Traceback (most recent call last):
  File "./gopro-py-api/examples/launch_webcam_preview.py", line 6, in <module>
    sys.argv[1]), camera=constants.gpcontrol, webcam_device=sys.argv[1])
IndexError: list index out of range

**Comment by KonradIT** [comment]
You're supposed to put your interface as an argument.

**Comment by lukiifaz** [comment]
Rpi3b + with octoprint, hero5 sesion is conected to rpi via wifi, rpi is conected to internet via ethernet. You mean network interface? Any example?

**Comment by KonradIT** [comment]
>hero5 sesion is conected to rpi via wifi

Why are you trying to use the webcam example (which uses GoPro Connect functionality only found in Hero8 and 9 cameras) for the Hero5 Session?

**Comment by lukiifaz** [comment]
Because I didn't know it. So how do I preview octoprint. I have Domoticz and therefore I am looking for a solution with displaying the image in the browser.

**Comment by KonradIT** [comment]
You'll have to figure that out yourself since I don't have octoprint, or a 3d printer. There are tutorials out there for how to integrate GoPro into OctoPrint via OctoLapse.
