### ISSUE TITLE
"Camera successfully connected!" shows twice

### ISSUE THREAD

**Issue by Berryfier** [KonradIT/gopro-py-api#16]
Thank you for sharing your code. I'm using it on raspberry pi to connect with GoPro session 4. I've successfully sync'd the GoPro date and time. I notice that the "Camera successfully connected!" appears twice after >>> gpCam = GoProCamera.GoPro(constants.gpcontrol) is entered. Maybe exceptions to try are queued causing prepare_gpcontrol() to restart in another loop?

**Comment by KonradIT** [comment]
Yes, once the camera is woken up it checks again.

**Comment by Berryfier** [comment]
Then I'll not worry. Thanks again.
