### ISSUE TITLE
GoPro Hero9 freezout 

### ISSUE THREAD

**Issue by MaHDiaLaGaB** [KonradIT/gopro-py-api#187]
my camera stop and freez out when i give any command from my python code... even i need to remove the battery and put it back so i can open it again

**Comment by KonradIT** [comment]
Hi, please describe your problem more in detail. What do you mean freeze? Is the camera running over USB or over WiFi? What version is the Hero9 running?

**Comment by MaHDiaLaGaB** [comment]
Hi, oh I am sorry I forget to close the issue, It's Hero9 1.6 but I downgraded to 1.21, and now the shutter works good but shutter close for videos doesn't work at all.
