### ISSUE TITLE
Using GoPro (Hero 9) for Octolapse

### ISSUE THREAD

**Issue by PaWi20** [KonradIT/gopro-py-api#204]
Hello there, 

I hope there is anybody who can help me. I want to use a GoPro (Hero 9) to record timelapses during 3D printing. My printer has OctoPrint and Octolapse installed. I followed a guide to install GPhoto 2 on the raspberry Pi (3b), that is used for OctoPrint. The raspberry pi can detect the gopro (command: gphoto2 --auto-detect), but I can't take a photo by using "gphoto2 --capture-image". The error message indicates that this operation is not supported.

As far as I understand I need to use the gopro-py-api in order to take photos. I have got less experience with Raspberry Pi and Phyton. Can someone explain the steps I need to make to create a script (?!) that allows me to take photos with the GoPro connected to the Raspberry Pi.

I also want to connect the GoPro with USB to the Pi (not WiFi). Is that even possible with the Hero 9? I also have a Hero 6 and 11 Mini. But that should not work with USB, correct?

I would be so grateful for any support. 

Best Wishes, Pascal

**Comment by KonradIT** [comment]
`gphoto` cannot interface with GoPro's wireless/wired control APIs afaik. There's some [discussion here](https://github.com/FormerLurker/Octolapse/issues/309) regarding OctoLapse and GoPro support.
