### ISSUE TITLE
My GoPro hero 7 does not apear in my WIFI list 

### ISSUE THREAD

**Issue by shahla-ai** [KonradIT/gopro-py-api#211]
@KonradIT 
Hello again
How can i make my GoPro Hero 7 apear on my WIFI list on Raspberry PI
i turned ON my wifi in the CAM , but still not available in WIFI list
Any Help please ?
best ragards

**Comment by KonradIT** [comment]
This is not a support forum for non-gopro hardware, I suggest asking in a RPI related site.
