### ISSUE TITLE
 urllib.request

### ISSUE THREAD

**Issue by isdito** [KonradIT/gopro-py-api#3]
hello,

Thank you for the post before.

What version of python need ? 

```
    import urllib.request
ImportError: No module named request
```
I have version 2.7 I need install another verison

**Comment by KonradIT** [comment]
you need python 3.6

**Comment by isdito** [comment]
OK I install. I go to check.
I need capture at 10 minutes and transfer to my computer it is more easy but I have more problems with another programs like Action camera tool box

**Comment by isdito** [comment]
The gpCam.downloadLastMedia() I could change the path to download, I dont know the path.

Thank you

**Comment by isdito** [comment]
OK I find it Current directory. I think that it is better selec a foder
import os
os.getcwd()

**Comment by KonradIT** [comment]
hi, as per the custom path for download:

gpCam.downloadLastMedia(custom_filename="/home/blahblah/Videos/GoPro/")
