### ISSUE TITLE
[Hero 6] Pairing screen stays visible, https pairing refuses connection

### ISSUE THREAD

**Issue by Calcyfer** [KonradIT/gopro-py-api#36]
I tried pairing the hero 6 through its LCD display (connections -> connect new device -> GoPro App). then connected to the correct SSID and tried .pair(), but the https port refuses connections.

All other commands work, but only while the LCD shows "pairing".

I've also tried configuring a router for the smart remote mode (correct MAC, SSID, DHCP), but in that mode, none of the ports are accessible.

Has anyone had success pairing the Hero6 with the latest firmware?

**Comment by KonradIT** [comment]
What's the terminal output when you pair?

**Comment by KonradIT** [comment]
For everyone wondering: 

    [gpcam] = GoPro...
    [gpcam].pair(usepin=False) \#For HERO5, 6.
