### ISSUE TITLE
overview() fails to parse FRAME_RATE 

### ISSUE THREAD

**Issue by 8bitben** [KonradIT/gopro-py-api#40]
Hi, in the overview() function, the API fails to correctly parse the frame rate. Current mode is 1080p80FPS. 

> HERO4 Black
HD4.02.05.00.00
Camera successfully connected!
camera overview
current mode: Video
current submode: Video
current video resolution: 1080pSV
Traceback (most recent call last):
  File "xxx", line 9, in <module>
    print(cam.overview())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/goprocam/GoProCamera.py", line 1083, in overview
    print("current video framerate: " + "" + self.parse_value("video_fr",self.getStatus(constants.Status.Settings, constants.Video.FRAME_RATE)))
TypeError: must be str, not NoneType

**Comment by KonradIT** [comment]
I fixed it in 7d15b1486df04d3b0ae61b6fc6f4634553b9afc1. Thanks!
