### ISSUE TITLE
class of values Photo.HDR shadows the parameter constant Photo.HDR

### ISSUE THREAD

**Issue by pderian** [KonradIT/gopro-py-api#45]
Perhaps the constants should be renamed Photo.HDR_PHOTO, following Photo.WDR_PHOTO?

https://github.com/KonradIT/gopro-py-api/blob/4176ba03e386be5d6477e8aad1006d6ac50c99a8/goprocam/constants.py#L457

**Comment by KonradIT** [comment]
I'm away from a computer, can you make a pull request with your suggestion?

**Comment by pderian** [comment]
Done, PR #46
