### ISSUE TITLE
Issues with ffmpeg not being recognized

### ISSUE THREAD

**Issue by Kortike** [KonradIT/gopro-py-api#54]
When running a basic example this is the output I get. Seems to be connecting fine, but no matter what I do ffmpeg is not recognized. I've downloaded, unzipped, and added ffmpeg to the PATH. I attempted a PIP install of ffmpeg but I get an error for subprocess (see below)

```
HERO+
HD3.22.01.50
Camera successfully connected!
{"status":"0"}


'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.
```

```
Could not find a version that satisfies the requirement subprocess (from ffmpeg) (from versions: )
No matching distribution found for subprocess (from ffmpeg)
```

Anyone else run into this issue before?

**Comment by heinzchen** [comment]
try this:
pip install ffmpeg-python
