### ISSUE TITLE
Hero7 support

### ISSUE THREAD

**Issue by var316** [KonradIT/gopro-py-api#66]
Hi Konrad, all, 

Has anyone made it work with Hero 7 Black or the support is still in progress? 

Cheers

**Comment by KonradIT** [comment]
It works with the 7 black. I've tested it myself.

**Comment by var316** [comment]
I've been trying to connect to the camera through the 'gpCam = GoProCamera.GoPro(constants.gpcontrol)' command with no success and stuck in 'Waking up...' state. 

And next I tried to connect by setting the mac_address through 'GoProCamera.GoPro("DC:53:60:20:EF:7C", constants.gpcontrol)' but this returns another error mentioned below:

![image](https://user-images.githubusercontent.com/5763906/47139579-72697a80-d2bc-11e8-9266-167038466a80.png)

Can you please tell me where am I going wrong?

**Comment by KonradIT** [comment]
Hi

Try with: GoProCamera.GoPro(constants.gpcontrol,  mac_address="DC:53:60:20:EF:7C")

**Comment by var316** [comment]
I tried with that and also with: 
GoProCamera.GoPro(constants.gpcontrol, ip_address="10.5.5.101", mac_address="DC:53:60:20:EF:7C")
but it still is stuck in the Waking Up state and eventually the camera wifi also disappears. Did you also face such problems with the GoPro wifi?

Many thanks for your support btw!

**Comment by KonradIT** [comment]
That's weird. Try with "dc536020ef7c" or install "getmac" module.

**Comment by KonradIT** [comment]
Proof it works with my HERO7 Black: https://streamable.com/v1879

**Comment by var316** [comment]
Hey, it works! I had changed the ip_address to the laptop ip_address (annoyingly) in the GoProCamera.py so it just works with the GoProCamera.GoPro(constants.gpcontrol) command itself.

**Comment by KonradIT** [comment]
Sweet.
