### ISSUE TITLE
Using getMediaInfo inside a script

### ISSUE THREAD

**Issue by joaolopes220** [KonradIT/gopro-py-api#7]
Hello,
Thanks for the library, it's very helpful.
I'm running into one problem, and I'm not really sure where to look at to solve.
When I run the functions as a command it works fine, and most of the functions work fine in a script as well.
However, when I run getMediaInfo inside a script it always returns an empty string. 

Thank you again

**Comment by KonradIT** [comment]
Hi.
Can you post the script? I think is because ```.getMediaInfo()``` ```returns``` a string, not ```print```, ```return``` works in the python REPL but not when running ```py script.py```. Try encapsulating your getMediaInfo line inside a ```print()``` statement.
![screenshot from 2017-06-13 08-52-36](https://user-images.githubusercontent.com/5891284/27069669-2745d834-5016-11e7-8226-acea820d03e6.png)

**Comment by joaolopes220** [comment]
Hello, sorry it took a while to get back.  
If I run something simple like this, I don't need to print the file name, I'm just trying to store it.  
If I run this then it fails to store it and gpfile is saved as an empty string.  I'm trying to get the file name saved so I can better track the videos, but also to use it to get the information of the hilight tags.  

gpCam = GoProCamera.GoPro()
gpCam.syncTime()
gpCam.shutter(constants.start)
time.sleep(5)
gpCam.shutter(constants.stop)
gpfile = gpCam.getMediaInfo('file')

**Comment by KonradIT** [comment]
@joaolopes220 using ```print(gpCam.getMediaInfo('file'))``` in a script works? Might be because the camera is not connected/turned off/supported
