### ISSUE TITLE
Screen of gopro on raspberry pi screen

### ISSUE THREAD

**Issue by tacleur** [KonradIT/gopro-py-api#80]
Hi everyone,

I want to play the screen of the GoPro Hero 6 on my raspberry pi screen (connected by HDMI).
The screen with and whitout any action. (just for that the people can see them before shoot).
My code is in python.

Have you some ideas  for do that?

Thanks a lot for your help.

**Comment by KonradIT** [comment]
This isn't really related to this API specifically, but to answer your question:

- Ensure the WiFi is up on the GoPro
- add a script that calls `stream("udp://127.0.0.1:10000")` on this API and then plays the stream using a player of your choice (VLC, MPV...)
