### ISSUE TITLE
How can i send a "stop video"?

### ISSUE THREAD

**Issue by tacleur** [KonradIT/gopro-py-api#82]
Hi,
Thanks a lot for your awesome API !
I work on a little project.
I can take a video but i want that the user can stop the video with a buton.
How can i stop the video with python code?

Thanks a lot

**Comment by yet-another-average-joe** [comment]
I'm experimeting with...

This script stops recording and it works ; it uses the shutter() function. it's in the docs section.

```
from goprocam import GoProCamera, constants
goproCamera = GoProCamera.GoPro()
goproCamera.shutter(constants.stop)

```

**Comment by KonradIT** [comment]
Yes that's how it's done.
