### ISSUE TITLE
Get Highlight status when recording video

### ISSUE THREAD

**Issue by OlivierHartmann** [KonradIT/gopro-py-api#85]
Hi,

Is it possible to connect to the camera (Hero7 Black), shooting a video and receiving highlight information in real time when the user is saying "Gopro HiLight"  or pushing the matching button. In fact there is a little notification on the Gopro screen, and not even a little "bip" sound.
Maybe a little broadcasted notification from the gopro else a little function to read that periodically (there is nothing returned when calling getVideoInfo() ).

Thank you

**Comment by KonradIT** [comment]
Not that I know of since `getMediaMetadata` of an in progress file is not possible.

**Comment by OlivierHartmann** [comment]
Thank you for your quick response.
