### ISSUE TITLE
File transfer performance issue

### ISSUE THREAD

**Issue by yet-another-average-joe** [KonradIT/gopro-py-api#88]
Hello KonradIT,

I had performance issues with gopro-py-api. Downloading a 5Mpx still from a GoPro Hero 3+ Black took 22 seconds on my RasPi 3 B+ !!!
I measured what you get on the Vimeo demo about the Hero 3. It takes 11 seconds.
On a smartphone with GoPro App, it takes 1~2 seconds.

Being deseperated, and suspecting a WiFi issue, I tried this  : I deactivated the onboard WiFi controller, and configured an USB dongle. And bingo ! Pics are transfered in a fingersnap.

This partially solved another issue : see #83 

Some thoughts ?

**Comment by KonradIT** [comment]
Yes, the RPI Wifi chip is not optimal.
