### ISSUE TITLE
Hero5 Black stuck on Waking up...

### ISSUE THREAD

**Issue by LachlanNXT** [KonradIT/gopro-py-api#9]
I can connect to Hero5 Black wifi and look at http://10.5.5.9/gp/gpControl in the browser, but when trying to initialize with:
`self.go = GoProCamera.GoPro(constants.gpcontrol)`
It will say Waking up... and not do anything further.
When I then connect using the phone app and try again it works fine.

**Comment by LachlanNXT** [comment]
Seems to be due to a loop in `prepare_gpcontrol()` that does not proceed until a certain status parameter is set, but when I tested removing this check it worked fine.

**Comment by KonradIT** [comment]
hi, can you make a pull request

**Comment by KonradIT** [comment]
fixed.
