### ISSUE TITLE
GoPro7 TimeWarp

### ISSUE THREAD

**Issue by wkitt** [KonradIT/gopro-py-api#90]
Will this support the new timewarp feature on the GoPro 7?

**Comment by KonradIT** [comment]
Hi, 

The API allows for changing [the TimeWarp speed](https://github.com/KonradIT/gopro-py-api/blob/f0781858da1418a6f8d3be10329fb366557299a7/goprocam/constants.py#L305) and switching to [TimeWarp mode](https://github.com/KonradIT/gopro-py-api/blob/f0781858da1418a6f8d3be10329fb366557299a7/goprocam/constants.py#L124)
